
##################################
# By:                            #
# Mail:                          #
# Ver: 5.2                       #
# Date:                          #
# ModuleName:Pyexception.py      #
##################################

##############################################################
#This python module is designed to hold any exception which  #
#is a special exception generated by the team                #
##############################################################

class NotAList(Exception): ###Created by Tal Potlog 5-Oct-2009### 
    def __init__(self,value):###This exception indicate that a variable is not a List###
        self.value=value
    def __str__(self):
        return repr("The Value given at variable %s  is not a list" % value)

class NotAString(Exception): ###Created by Tal Potlog 5-Oct-2009###
    def __init__(self,value):###This exception indicate that a varialbe is not a String###
         self.value=value
    def __str__(self):
        return repr("The Value given ( %s ) is not a string" % value.__str__)

class NotATuple(Exception): ###Created by Tal Potlog 5-Oct-2009###
     def __init__(self,value): ###This exception indicate that a varialbe is not a Tuple###
          self.value=value
     def __str__(self):
         return repr("The Value given ( %s ) is not a tuple" % value.__str__)

class NotATupleOrList(Exception): ###Created by Tal Potlog 5-Oct-2009###
    def __init__(self,value): ###This exception indicate that a varialbe is not a Tuple or a list###
        self.value=value
    def __str__(self):
        return repr("The Value given ( %s ) is not a tuple or a list" % value.__str__)
